### ISSUE TITLE
zsh: parse error near `)'

### ISSUE THREAD

**Issue by rowild** [Haroenv/mac-processor-info#1]
Hi!

With zsh i get the above mentioned error. 
Any idea what could be wrong?

Thanks!

**Comment by Haroenv** [comment]
the script is for bash, not zsh, but the zsh version would be:

```zsh
open "http://ark.intel.com/search?q=$(sysctl -n machdep.cpu.brand_string | awk '{print $3}')"
```

(with extra quotes)

**Comment by rowild** [comment]
@Haroenv Thank you very much for your reply and the solution!!!
